token: 
device_id: 
name: 
server_address: 
password: 
ip: 
server_encrypt: 
cipher_model: 
# 高级参数
tap: false #是否使用tap 仅在windows上支持使用tap
stun_server: #stun服务器
  - stun.miwifi.com
  - stun.chat.bilibili.com
  - stun.hitv.com
  - stun.cdnbye.com
# in_ips: #代理ip入站
#   - 0.0.0.0/0
# out_ips: #代理ip出站
#   - 0.0.0.0/0
mtu: 1420  #mtu
tcp: false #tcp模式
use_channel: all #relay:仅中继模式.p2p:仅直连模式
parallel: 1 #任务并行度
finger: false #关闭数据指纹
punch_model:  all #打洞模式，表示只使用ipv4地址打洞，默认会同时使用v6和v4
ports:
  - 0 #使用随机端口，tcp监听此端口
  - 0
cmd: false #关闭控制台输入
no_proxy: false #是否关闭内置代理，true为关闭
first_latency: false #是否优先低延迟通道，默认为false，表示优先使用p2p通道
device_name: vnt-tun #网卡名称
packet_loss: 0 #指定丢包率 取值0~1之间的数 用于模拟弱网
packet_delay: 0 #指定延迟 单位毫秒 用于模拟弱网
dns:
  - 223.5.5.5 # 首选dns
  - 114.114.114.114 # 备选dns  - 223.5.5.5 # 首选dns
  - 8.8.8.8 # 备选dns
# mapping:
#   - udp:0.0.0.0:80-10.26.0.10:80 # 映射udp数据
#   - tcp:0.0.0.0:80-10.26.0.10:81 # 映射tcp数据
#   - tcp:0.0.0.0:82-localhost:83 # 映射tcp数据
disable_stats: false # 为true表示关闭统计
allow_wire_guard: false # 为true则表示允许接入wg