token: 
device_id: 
device_name: 
server: 
password: 
ip: 
compress: false
cipher_model: aes_gcm
server_encrypt: true
cert_mode: skip

# 高级参数
# rtx: false  # 是否启用quic优化传输
# fec: false  # 是否启用 FEC 前向纠错
# no_punch: false  # 是否关闭 P2P 打洞
# mtu: 1400  # MTU 设置
# ctrl_port: 11233  # 控制服务的 tcp 端口
# tunnel_port: 0  # 隧道端口，用于P2P通信 (默认为0，自动分配)
# tun_name: vnt-tun  # 虚拟网卡名称
# no_tun: false  # 是否关闭TUN虚拟网卡
# no_nat: false  # 是否关闭内置子网NAT
# allow_mapping: false  # 是否允许作为端口映射出口
# port_mapping: []  # 端口映射
# input: []  # 入栈监听网段
# output: []  # 出栈允许网段
# udp_stun: []  # 自定义udp stun地址
# tcp_stun: []  # 自定义tcp stun地址
